# Generated by Django 4.0 on 2023-02-19 08:19

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title_tag', models.CharField(default='MyWeCode', max_length=255)),
                ('meta_description', models.CharField(default='MyWeCode', max_length=255)),
                ('meta_keywords', models.CharField(default='MyWeCode', max_length=255)),
                ('alt_tag', models.CharField(blank=True, max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('page_banner', models.ImageField(upload_to='about/%Y/%m/%d/')),
                ('about_image', models.ImageField(upload_to='about/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'about',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact Us',
            },
        ),
    ]
